PYTHONPATH=src pyanalyze --verbose --enable-all ./src
Checking file: ('./src/challenge/__init__.py', 10092)
./src/challenge/__init__.py took 0.00 s
Checking file: ('./src/challenge/main.py', 10092)
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
exception calling: (KnownValue(val=<method '__getitem__' of 'list' objects>), IndexError('list index out of range'))
./src/challenge/main.py took 0.30 s
Checking file: ('./src/test/__init__.py', 10092)
./src/test/__init__.py took 0.00 s
Checking file: ('./src/test/test_main.py', 10092)
./src/test/test_main.py took 0.22 s

real	0m1.693s
user	0m1.548s
sys	0m0.133s

